### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/quiet-flutter#1]
Thanks for your work!

When i'm try to run your project it get message like below
No implementation found for method encrypt on channel tech.soit.netease/crypto

please help me . 

thanks again.

**Comment by boyan01** [comment]
Are you running the ios version? i am sorry that i haven't  implement the method channel for iOS.

**Comment by phuongphally** [comment]
Thanks your answer. 
Now I'm fixed it and working. 

But why audio can not play in background ? Can you tell me where can I change it to work in background ?

**Comment by boyan01** [comment]
playback service has not been added yet . audio playback part is still under development .

**Comment by phuongphally** [comment]
How can I join your project? 

I like to work with music app.

**Comment by boyan01** [comment]
I am very happy and thank you for your willingness to participate in this project.

You can fork this project , commit your changes to you forked project.
then you can create a pull request from a fork. [https://help.github.com/articles/creating-a-pull-request-from-a-fork/](details).

**Comment by boyan01** [comment]
All API information comes from this project, [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) . but this is all written in Chinese , it might a bit difficult for you.

**Comment by phuongphally** [comment]
I'll try to understand . Thanks

**Comment by boyan01** [comment]
maybe you can try this way.
https://stackoverflow.com/questions/49508322/flutter-listview-lazy-loading

**Comment by phuongphally** [comment]
Hello @boyan01  

Can you help me change audio player work in background when device is locked screen? 

I need it urgent . 

If can please help me . 

Thanks .

**Comment by boyan01** [comment]
well, ok. I will try add this feature this weekend.

Phuong Phally (ភួង ផល្លី) <notifications@github.com>于2018年12月6日 周四下午5:36写道：

**Comment by phuongphally** [comment]
Really thanks to you @boyan01. 
I'm waiting from you.
