### ISSUE TITLE
ios 只有首页还行  其它都看不了

### ISSUE THREAD

**Issue by eleanors** [boyan01/quiet-flutter#26]

**Comment by boyan01** [comment]
这我也没啥办法呀，我也不会开发iOS，所以一些 Native 的方法没有在 iOS  平台上实现。

**Comment by boyan01** [comment]
现在大部分页面在ios上应该可用了，除了播放功能。

**Comment by dengp** [comment]
> 现在大部分页面在ios上应该可用了，除了播放功能。

pod找不到music_player，怎么解决呀

**Comment by boyan01** [comment]
> 
> pod找不到music_player，怎么解决呀

最新的代码重新设计了 Player 的架构，可能导致了 iOS 的构建出现了问题。（如果你能够修复这个问题的话，非常欢迎提交 PR~~）

所以目前想运行项目的话，有两种方式

1. 构建 Android APK
2. 使用未重构的旧版本 v0.2
```dart
 git checkout v0.2
```
