### ISSUE TITLE
Download Feature 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/quiet-flutter#27]
Hello I'm using your code to download. But can not get it working. 

Can you help me sample for download ?

**Comment by boyan01** [comment]
download feature was broken.
And because of the copyright limitation of music api, i am going to removing this feature in future.

So i'm sorry that i can not help you in this moment.

**Comment by phuongphally** [comment]
I'm see you code implemented by never used , And i'm don't know how to use too. 

Thanks

**Comment by boyan01** [comment]
i'm using this repo to implement Download.

maybe you can figure out how to use by read this library' docs.

https://github.com/tonyofrancis/Fetch

**Comment by phuongphally** [comment]
Thanks
