### ISSUE TITLE
SeekTo method work not correct.

### ISSUE THREAD

**Issue by phuongphally** [boyan01/quiet-flutter#5]
I'm get error message 

 'value >= min && value <= max': is not true

  onChanged: (value) {
              quiet.seekTo(value.round());
    },

**Comment by boyan01** [comment]
Thank you for submitting the bug, I will try to fix this bug right away.

**Comment by phuongphally** [comment]
@boyan01 Maybe Because of I'm get error 'value >= min && value <= max': is not true that why the audio not play next.

**Comment by boyan01** [comment]
Actually the reason is that i can not do it .  I used video_player dependency to play audio  before , this library do not provide complete callback to listen the audio if reach end.

**Comment by phuongphally** [comment]
@boyan01 Can I'm contact you by skype or any chat app ?

**Comment by boyan01** [comment]
I do not have skype id , do you have WeChat or telegram account?

**Comment by phuongphally** [comment]
@boyan01  I'm have telegram. My phone +85593883292. I'm you don't see please let me know your id then I'm will add to you . 
Thanks

**Comment by boyan01** [comment]
My telegram account seems be limited,can only send messages to mutual contacts, My phone number is +8618500469080

**Comment by boyan01** [comment]
Or you can contact my by email. yangbinyhbn@gmail.com

**Comment by boyan01** [comment]
fixed b4d5c26aad8294fafadf1ec3630b3c6e9fd92432

**Comment by phuongphally** [comment]
@boyan01 Thanks
